### ISSUE TITLE
Walldt download

### ISSUE THREAD

**Issue by iamdrainbows** [xnodevps-project/xnode#1]
I downloaded the windows version and Mac os on iPad.  
It said could not run on windows and it didn't do anything when I opened it on iPad.  Please help.  I'm buying a masternode this week and I need to get prepared for this. I used my graviex wallet on a shared masternode and I'm not getting my rewards on crypos.io

**Comment by xnodevps-project** [comment]
hello sir, both the wallet windows & mac os are working fine, non of the community members are complaining about the issue. Mac osx wallet will work on mac laptops or desktop or mac mini running mac osx. It will not work on ipad as its runs ipad os not mac osx.
